# Travis CI (MIT License) configuration file for the BP-REST
# @link https://travis-ci.org/

# Setting dist.
dist: xenial

# Setting OS.
os: linux

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Setting services.
services:
  - mysql

branches:
  only:
    - master
    - main

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# Git clone depth.
git:
  depth: 1
  quiet: true

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"

jobs:
  fast_finish: true
  include:
    - stage: sniff
      script:
        - composer lint
        - composer phpcs
      env: BUILD=sniff
    - stage: test
      php: 8.0
      env: WP_VERSION=latest
    - stage: test
      php: 7.4
      env: WP_VERSION=latest
    - stage: test
      php: 7.3
      env: WP_VERSION=latest
    - stage: test
      php: 7.2
      env: WP_VERSION=latest
    - stage: test
      php: 7.1
      env: WP_VERSION=latest
    - stage: test
      php: 7.0
      env: WP_VERSION=latest
    - stage: test
      php: 5.6
      env: WP_VERSION=latest
    allow_failures:
      - php: 8.0
        env: WP_VERSION=latest

before_install:
  - |
    # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
    phpenv config-rm xdebug.ini || echo "Xdebug not available"

  - |
    # Raise PHP memory limit to 2048MB
    echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  - |
    # Validate composer
    composer validate --strict

install:
  - composer install
  - composer prepare-tests

script:
  - composer behat || composer behat-rerun

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: false
